config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  get 'grandparents', to: 'grandparents#index'
  get 'grandparents/new', to: 'grandparents#new'
  get 'grandparents/:id', to: 'grandparents#show', as: :grandparent
  post 'grandparents', to: 'grandparents#create'
  get 'bookings', to: 'bookings#index', as: :bookings
  post 'grandparents/:id/bookings/', to: 'bookings#create'
  # get 'grandparents/:id/edit', to: "grandparents#edit", as: :edit_grandparent
  # patch 'grandparents/:id', to: "grandparents#update"
  delete "grandparents/:id", to: "grandparents#destroy"
  get 'my_grandparents', to: 'grandparents#mygrandparents', as: :my_grandparents
  #get 'grandparents/:id/bookings/new', to: 'bookings#new', as: :bookings_new

  get 'bookings/:id', to: 'bookings#show', as: :show_booking
  resources :grandparents, only: [:show, :edit, :update ] do
    resources :bookings, only: [:new, :create]
  end

  get 'requests', to: 'bookings#owner_bookings'

  patch 'bookings/:id/accept', to: 'bookings#accept', as: :booking_accept
  patch 'bookings/:id/decline', to: 'bookings#decline', as: :booking_decline
  # resources :bookings, only: [] do
  #   patch :accept
  #   patch :decline
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :grandparent

  validates :price, presence:true
  validates :start_date, presence:true
  validates :end_date, presence:true

  enum status: {
    pending: 0,
    accepted: 1,
    declined: 2
  }
end

app/models/grandparent.rb
class Grandparent < ApplicationRecord
  belongs_to :user
  has_many :bookings
  # has_many :reviews

  validates :name, presence: true, length: { minimum: 2 }
  validates :age, presence: true, numericality: true
  validates :abilities, presence: true, length: { maximum: 500 }
  validates :limitations, presence: true, length: { maximum: 500 }
  validates :language, presence: true
  validates :daily_rate, presence: true, numericality: true
  validates :location, presence: true
  validates :phone_number, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_one_attached :photo



  include PgSearch::Model
  pg_search_scope :search_by_name_age_abilities_language_location,
  against: [ :name, :age, :abilities, :language, :location ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :grandparents, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # validates :first_name, presence: true, length: { minimum: 2 }
  # validates :last_name, presence: true, length: { minimum: 2 }
  # validates :language, presence: true
  # validates :location, presence: true
  # validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   # For additional fields in app/views/devise/registrations/new.html.erb
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  #   # For additional in app/views/devise/registrations/edit.html.erb
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def article_params
    params.require(:article).permit(:title, :body, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy accept decline]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def owner_bookings
    @bookings = Booking.where(grandparent: current_user.grandparents)
  end

  def show
  end

  def new
    @grandparent = Grandparent.find(params[:grandparent_id])
    @booking = Booking.new
  end

  def create
    @grandparent = Grandparent.find(params[:id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.grandparent = @grandparent
    @booking.price = @grandparent.daily_rate
    if @booking.save
      redirect_to bookings_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  # end

  # def update
  #   booking.update(booking_params)
  #   redirect_to booking_path(@booking)
  # end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

# PATCH /offers/:id/accept
  # @TODO authorize that the user should actually be allowed the offer
  def accept
    if @booking.accepted!
      redirect_to requests_path, notice: 'Booking accepted'
    else
      redirect_to requests_path, notice: 'Booking could not be accepted - please try again'
    end
  end

    # PATCH /offers/:id/reject
  # @TODO authorize that the user should actually be reject the offer
  def decline
    if @booking.declined!
      redirect_to bookings_path, notice: 'Booking rejected'
      @booking.destroy
    else
      redirect_to bookings_path, notice: 'Booking could not be rejected - please try again'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :price)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/grandparents_controller.rb
class GrandparentsController < ApplicationController
  before_action :grandparent, only: [:show, :edit, :update, :destroy]


  def index
    @grandparents = Grandparent.all
    @markers = @grandparents.geocoded.map do |grandparent|
      {
        lat: grandparent.latitude,
        lng: grandparent.longitude
      }
    end

    if params[:query].present?
      @grandparents = Grandparent.search_by_name_age_abilities_language_location(params[:query])
    else
      @grandparents = Grandparent.all
    end
  end

  def show
  end

  def new
    @grandparent = Grandparent.new
  end

  def create
    @grandparent = Grandparent.new(grandparent_params)
    @grandparent.user = current_user
    if @grandparent.save
      redirect_to grandparent_path(@grandparent)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @grandparent = Grandparent.find(params[:id])
  end

  def update
    @grandparent = Grandparent.find(params[:id])
    @grandparent.update(grandparent_params)
    redirect_to grandparent_path(@grandparent)
  end

  def destroy
    @grandparent = Grandparent.find(params[:id])
    @grandparent.destroy
    redirect_to grandparents_path, status: :see_other
  end

  def mygrandparents
    @grandparents = Grandparent.where(user: current_user)
  end



  private

  def grandparent_params
    params.require(:grandparent).permit(:name, :age, :abilities, :limitations, :phone_number, :language, :location, :daily_rate, :photo)
  end

  def grandparent
    @grandparent = Grandparent.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: :home

  def home
    @featured_grandparents = Grandparent.all.first(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/show.html.erb
<%= cl_image_tag @article.photo.key, height: 80, width: 150 %>

app/views/bookings/_bookings.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Booking with</strong><%= booking.grandparent.name %>
  </p>

  <p>
    <strong>From:</strong>
    <%= booking.start_date %>
  </p>

  <p>
    <strong>To:</strong>
    <%= booking.end_date %>
  </p>

  <p>
    <strong>Grandparent will do:</strong>
    <%= booking.grandparent.abilities %>
  </p>

 </div>

app/views/bookings/_form.html.erb
<%= simple_form_for([grandparent, booking]) do |f| %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>

  <div class="btn1">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<p style="color: blue"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <li><%= "Booking with : #{booking.grandparent.name}"%></li>
     <li><%= "from #{booking.start_date}"%></li>
     <li><%= "to #{booking.end_date}"%></li>
    <li><%= "Price: $#{booking.price}"%></li>
    <li><%= "Status: #{booking.status}"%></li>
    <p>
      <%= button_to "BOOKING DETAILS", show_booking_path(booking), class: 'btn1' %>
      <% if booking.grandparent.user == current_user %>
        <%= button_to "Accept", booking_accept_path(booking), class: 'btn1', method: :patch %>
        <%= button_to "Decline", booking_decline_path(booking), class: 'btn1', method: :patch %>
      <% end %>
    </p>
  <% end %>
</div>
<div style="height:100vh"></div>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking, grandparent: @grandparent %>

<br>

<div>
  <%= link_to "Check all bookings", bookings_path %>
</div>

app/views/bookings/owner_bookings.html.erb
<p style="color: blue"><%= notice %></p>

<h1>Requests for me</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <li><%= "Booking with #{booking.grandparent.name} from #{booking.start_date} to #{booking.end_date}"%></li>
    <li><%= "Price: $#{booking.price}"%></li>
    <li><%= "Status: #{booking.status}"%></li>
    <p>
      <%= link_to "Show this booking", show_booking_path(booking) %>
      <% if booking.pending? %>
        <%= button_to "Accept", booking_accept_path(booking), class: 'btn1', method: :patch %>
        <%= button_to "Decline", booking_decline_path(booking), class: 'btn1', method: :patch %>
      <% end %>
    </p>
  <% end %>
</div>

<div style="height:100vh"> </div>

app/views/bookings/show.html.erb
<%= render "bookings", booking: @booking %>
<div style="height:100vh"></div>

app/views/grandparents/_form.html.erb
<%= simple_form_for(@grandparent) do |f| %>

  <div class="card2">
    <%= f.input :name %>
    <%= f.input :language %>
    <%= f.input :age %>
    <%= f.input :abilities %>
    <%= f.input :limitations %>
    <%= f.input :phone_number %>
    <%= f.input :location %>
    <%= f.input :daily_rate %>
    <%= f.button :submit, class: 'btn1' %>
  </div>
<% end %>

app/views/grandparents/_grandparents.html.erb
<div id="<%= dom_id grandparent %>">
  <p>
    <strong>Name:</strong>
    <%= grandparent.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= grandparent.age %>
  </p>

  <p>
    <strong>Abilities:</strong>
    <%= grandparent.abilities %>
  </p>

  <p>
    <strong>Limitations:</strong>
    <%= grandparent.contradictions %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= grandparent.language %>
  </p>

    <p>
    <strong>Location:</strong>
    <%= grandparent.location %>
  </p>

  <p>
    <strong>Daily Rate:</strong>
    <%= grandparent.daily_rate %>
  </p>

  <% if grandparent.user == current_user %>
        <%= button_to “Edit”, edit_grandparent_path %>
        <%= button_to “Delete”, grandparent_path(@grandparent),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
      <% end %>

</div>

app/views/grandparents/_index.html.erb
<p style="color: blue"><%= notice %></p>

<h1>Grandparents</h1>

<div id="grandparents">
  <% @grandparents.each do |grandparent| %>
    <%= render grandparent %>
    <p>
      <%= link_to "Open listing", grandparent %>
    </p>
  <% end %>
</div>

<%= link_to "New listing", new_grandparent_path %>

app/views/grandparents/_new.html.erb
<h1>New listing</h1>

<%= render "form", grandparent: @grandparent %>

<br>

<div>
  <%= link_to "Back to listings", grandparents_path %>
</div>

app/views/grandparents/edit.html.erb
<h1>Edit your Grandparent</h1>

<div class="form-inputs">
<%= simple_form_for(@grandparent) do |f| %>
    <%= f.input :name %>
    <%= f.input :language %>
    <%= f.input :age %>
    <%= f.input :abilities %>
    <%= f.input :limitations %>
    <%= f.input :phone_number %>
    <%= f.input :location %>
    <%= f.input :daily_rate %>
    <%= f.button :submit %>
    <% end %>
  </div>

app/views/grandparents/index.html.erb
<%= form_with url: grandparents_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a grandparent"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<h1>Grandparents near you</h1>

<div class="d-flex" >

  <div class="container" id="grandparents" >
    <div class="row">
      <% @grandparents.each do |grandparent| %>
        <%= render "shared/grandparent_card", grandparent: grandparent %>
      <% end %>
    </div>
  </div>
</div>

<p><%= button_to 'ADD A GRANDPARENT', grandparents_new_path, class: "btn1", method: :get %></p>
<p><%= button_to 'GO BACK TO HOME PAGE', root_path, class: "btn1", method: :get %></p>



<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/grandparents/mygrandparents.html.erb
<h1>My grandparents</h1>

 <% @grandparents.each do |grandparent| %>
    <li>
      <%= link_to grandparent.name, grandparent %>
    </li>
  <% end %>
  
<div style="height:100vh"> </div>

app/views/grandparents/new.html.erb
<h1>Add grandparents</h1>

<%= render "form", grandparent: @grandparent %>

<p><%= button_to 'GO BACK', grandparents_path, class: 'btn1', method: :get %></p>

app/views/grandparents/show.html.erb
<div class="container">
  <h1><%= @grandparent.name %>'s Profile</h1>

  <div>
    <%= cl_image_tag @grandparent.photo.key, class: "card-user", width: 160, height: 190 %>
  </div>

  <div class='details'>
    <strong>Talents:</strong>
    <%= @grandparent.abilities%>
  </div>

  <div class='details'>
    <strong>Limitations:</strong>
    <%= @grandparent.limitations%>
  </div>

  <div class='details'>
    <strong>Mother tongue:</strong>
    <%= @grandparent.language %>
  </div>

  <div class='details'>
    <strong>Daily rate:</strong>
    <%= @grandparent.daily_rate %>
  </div>

  <div class='details'>
    <strong>Location:</strong>
    <%= @grandparent.location %>
  </div>
</div>

<<<<<<< HEAD

<p><%= button_to 'MAKE A BOOKING', new_grandparent_booking_path(@grandparent), class: 'btn1', method: :get %></p>
=======
<% if @grandparent.user != current_user %>
<p><%= button_to 'Make a booking', new_grandparent_booking_path(@grandparent), method: :get %></p>
<% end %>
>>>>>>> 693d0f877d9c7e87bdc5a175ee8222637dea13ec

<% if @grandparent.user == current_user %>
  <p><%= button_to 'EDIT', edit_grandparent_path(@grandparent), class: "btn1", method: :get %></p>
  <p><%= button_to 'DELETE', grandparent_path(@grandparent), class: 'btn1"', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, method: :delete %></p>
<% end %>

<<<<<<< HEAD
<p><%= button_to 'GO BACK TO GRANDPARENTS', grandparents_path, class: 'btn1', method: :get %></p>
=======
<p><%= button_to 'Back to grandparents', grandparents_path, method: :get %></p>
<div style="height:100vh"></div>
>>>>>>> 693d0f877d9c7e87bdc5a175ee8222637dea13ec

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrandRentals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <div class="main-container"> %>
  <div class="h1-search-bar">
    <h4>Feel lonely? Rent grandparents!</h4>
    <input type="text" class="search-bar" placeholder="Search for grandparents...">

  <%# <div class="container" id="grandparents"> %>
  <%# <h2 class="text-center">Featured grandparents</h2>
  <div class="row">
    <% @featured_grandparents.each do |grandparent| %>
      <%# <%= render "shared/grandparent_card", grandparent: grandparent %>
    <%# <% end %>
  <%# </div> %>
<%# </div> %>


<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))url(https://files.slack.com/files-pri/T02NE0241-F04R1B566JK/image.png)">
    <div class="container">
      <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
      <p>Change your life and learn to code at one of our campuses around the world.</p>
      <a class="btn btn-flat" href="#">Apply now</a>
    </div>
    <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" />
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Search
        </button>
      </div>
    </form>
      <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <%# <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div> %>
    </div>
<%#
</body>
</html> %>

<div style="height:100vh"> </div>

app/views/pages/listings.html.erb
 <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0) 100%), img src='app/assets/images/istockphoto-1388964325-170667a.jpg' alt="grandparent">
          <div class="card-category">Grandparent1</div>
          <div class="card-description">
            <h3>Grandparent 1</h3>
            <p class="rating">
                <i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #cacccd"></i>
            </p>
          </div>
          <img src="https://res.cloudinary.com/dkitmi74n/image/upload/v1677788391/5003730f7cdfc06ae982f3dc2ae8c5a1_or1x3w.jpg"  class="card-user" alt="Grand1">
          <%# <a href="flats/ssaunier.html" class="card-link"></a> %>
        </div>
      </div>

app/views/shared/_button.html.erb
<a class="btn btn-gradient <%= color %> " href="#">Search</a>

<a class="btn btn-gradient" href="#">Login</a>

<a class="btn btn-gradient" href="#">Sign up</a>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_grandparent_card.html.erb
<<<<<<< HEAD
<div class="col-xs-12 col-sm-6 col-md-4">
  <div class="card1" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0) 100%), img src='app/assets/images/istockphoto-1388964325-170667a.jpg' alt="grandparent">
=======
<div class="col-xs-12 col-auto sm-6 md-4 mb-3">
  <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0) 100%), img src='app/assets/images/istockphoto-1388964325-170667a.jpg' alt="grandparent">
>>>>>>> 693d0f877d9c7e87bdc5a175ee8222637dea13ec
    <div class="card-category"> </div>
    <div class="card-description">
    <%= cl_image_tag grandparent.photo.key, class: "card-user", width: 160, height: 190 %>
      <h3 style="text-decoration: none"><%= link_to grandparent.name, grandparent %></h3>

<<<<<<< HEAD

      <p> Location: </p>
      <p> Daily rate:   </p>
      <%# <p><%= link_to grandparent.bio, grandparent</p> %>
      <%# <p class="rating"> %>
          <%# <i class="fa fa-star" style="color: #ffb400"></i> %>
          <%# <i class="fa fa-star" style="color: #ffb400"></i> %>
          <%# <i class="fa fa-star" style="color: #ffb400"></i> %>
          <%# <i class="fa fa-star" style="color: #ffb400"></i> %>
          <%# <i class="fa fa-star" style="color: #cacccd"></i> %>
      <%# </p> %>
=======
    <%# <a href="flats/ssaunier.html" class="card-link"></a> %>
      <p>Age: <%= grandparent.age %></p>
      <p>Location: <%= grandparent.location %></p>
      <p>Daily rate: $<%= grandparent.daily_rate %></p>
      <%# <p class="rating">
          <i class="fa fa-star" style="color: #ffb400"></i>
          <i class="fa fa-star" style="color: #ffb400"></i>
          <i class="fa fa-star" style="color: #ffb400"></i>
          <i class="fa fa-star" style="color: #ffb400"></i>
          <i class="fa fa-star" style="color: #cacccd"></i> %>
      </p>
>>>>>>> 693d0f877d9c7e87bdc5a175ee8222637dea13ec
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-top-0 shadow-sm mb-5">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.grandrentals avatar.png",  alt: "GR Logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Index", "/grandparents", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New", "/grandparents/new", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Grandparents", "/my_grandparents", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", "/bookings", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Requests", "/requests", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "/assets/avatar_unknown", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>